#!/bin/bash

function usage() {
        echo
        echo "Host This"
        echo
        echo "   Parameters:"
        echo
        echo "        -h: print this help doc"
        echo 
        echo "   Examples:"
        echo 
        echo
}

function hostthis() {
        if [[ $# == "0" ]]; then
                writehost
        else
                switchboard $@
        fi
}

function switchboard() {
        while getopts ":ho" optname
        do
                case "$optname" in
                        "o")
                                openconf
                                exit
                                ;;
                        "h")
                                usage
                                exit
                                ;;
                        "?")
                                echo "Unknown option $OPTARG"
                                ;;
                        ":")
                                case "$OPTARG" in
                                        "f")
                                                echo "Argument $OPTARG requires a filename"
                                                exit
                                                ;;
                                        "t")
                                                echo "Argument $OPTARG requires a tag name"
                                                exit
                                                ;;
                                        *)
                                                echo "Argument $OPTARG requires a value"
                                                ;;
                                esac
                                ;;
                        *)
                                # Should not occur
                                echo "Nothing to do"
                                ;;
                esac
                # echo "OPTIND is now $OPTIND"
        done
}

function writehost() {
	directory=$(pwd)

	name="example.local"

	echo "Enter local domain name (ex. '$name'):"
	read name

	echo "<VirtualHost *:80>" >> /etc/httpd/conf/httpd.conf
	echo "DocumentRoot \"$directory\"" >> /etc/httpd/conf/httpd.conf
	echo "ServerName $name" >> /etc/httpd/conf/httpd.conf
	echo "ServerAlias *.$name" >> /etc/httpd/conf/httpd.conf
	echo "</VirtualHost>" >> /etc/httpd/conf/httpd.conf

	# echo "<VirtualHost *:80>"
	# echo "DocumentRoot \"$directory\""
	# echo "ServerName $name"
	# echo "ServerAlias *.$name"
	# echo "</VirtualHost>"
}

function openconf() {
        sudo nano /etc/httpd/conf/httpd.conf
}

hostthis $@